[network_config]
node = 'LSH'
des = 'deeqcm'

[DDP]
world_size = 1   # number of available gpus

[optimizer]
lr = 1e-3

[loss]
loss_func = 'hybrid'

[listener]
listener_sr = 16000

[FFT]
n_fft = 512
hop_length = 256
win_length = 512

[train_dataset]
train_folder = '/root/aec/AEC-Challenge2022/datasets/synthetic/train_set.csv'
shuffle = true
num_tot = 0
wav_len = 0

[train_dataloader]
batch_size = 10
num_workers = 2
drop_last = true
pin_memory = true

[validation_dataset]
train_folder = '/root/aec/AEC-Challenge2022/datasets/synthetic/val_set.csv'
shuffle = true
num_tot = 0
wav_len = 0

[aecmos]
aecmos = '/root/aec/SEtrain/AECMOS_local/Run_1663829550_Stage_0.onnx'


[validation_dataloader]
batch_size = 1
num_workers = 0
pin_memory = true

[trainer]
epochs = 120
save_checkpoint_interval = 1
clip_grad_norm_value = 3.0
exp_path = '/root/aec/SEtrain/exp/exp'
resume = false
resume_datetime = '2023-12-08-18h48m'
resume_step = 15