path:
  exp_folder: ${network.root}/${network.exp_name}/${network.cpt_name}/enhanced # where enhanced speech store
  csv_folder: ${network.root}/${network.exp_name}/${network.cpt_name}/
network:
  root: /root/aec/SEtrain/exp
  exp_name: exp_2023-11-29-17h30m
  cpt_name: best_model_0101
  checkpoint: ${network.exp_path}/checkpoints/${network.cpt_name}.tar
  exp_path: ${network.root}/${network.exp_name}
  cfg_toml: ${network.exp_path}/config.toml

